### ISSUE TITLE
qt5-virt-manager quit unexpectedly.

### ISSUE THREAD

**Issue by cmsimike** [F1ash/homebrew-qt-virt-manager#1]
Hi,

Tried installing your homebrew and qt5-virt-manager keeps crashing with the above error.

**Comment by cmsimike** [comment]
FWIW, the viewer doesn't crash. Just the manager

**Comment by F1ash** [comment]
Strange... Maybe you can to write some additional information: building was successful; it was first start of application without any custom (by defuault) settings; the app crash at each start; etc.

**Comment by cmsimike** [comment]
hi - yes it was right after I installed it. It seemed to compile without a problem. It crashes at startup each time - i briefly (very briefly) see the UI before it crashes. No custom anything - just installed via homebrew and ran.

osx 10.12 (latest patch release).

**Comment by F1ash** [comment]
https://paste.fedoraproject.org/510294/27020814/
this bug trace displays that this crash occures in (qt gui) main thread. Therefore i think that it is a qt bug, not app code bug, because on another mac releases it not occures.

**Comment by cmsimike** [comment]
What are the specs of the other mac? Could a fix already be available in the dependency?

**Comment by isage** [comment]
Nope. It seems like some qt or libvirt incompatibility with Sierra.
It doesn't crash on previous osx versions.

**Comment by cmsimike** [comment]
Thank you!

**Comment by deasmi** [comment]
Also seeing this - https://gist.github.com/deasmi/aa2f53bb827997e1e4a013d6a446c355 - if it's any help.

**Comment by F1ash** [comment]
i updated home brue. Pls, try to do build. I did make some fix in main.cpp, maybe will helpful.

**Comment by cmsimike** [comment]
Fixed it for me! Thank you very much!!

**Comment by deasmi** [comment]
Also fixed for me, thank you for the very quick fix.
