### ISSUE TITLE
Missing , (comma) in Line 5 (qt-virt-manager.rb)

### ISSUE THREAD

**Issue by iGeorgeX** [F1ash/homebrew-qt-virt-manager#2]
In Line 5 (:revision => "158e00fb54d946263fc180b92b974a1381145c75") is a , (comma) missing

url "https://github.com/F1ash/qt-virt-manager.git",
:revision => "158e00fb54d946263fc180b92b974a1381145c75"
:using => :git

https://github.com/F1ash/homebrew-qt-virt-manager/commit/8fb285349082cb99542320b1cbf016fc00d3887b

**Comment by F1ash** [comment]
fixed.
